### ISSUE TITLE
Config for IPv6

### ISSUE THREAD

**Issue by renatillas** [stndrs/based_pg#2]
I've recently migrated from pgo to based but I've faced that my database uses ipv6 instead of ipv4. The based_pg.Config type does not provide a field to set the ip type and would like a way to set it up. Thank you!

**Comment by renatillas** [comment]
I've created this PR to solve the issue, although its a breaking change: https://github.com/stndrs/based_pg/pull/3

**Comment by stndrs** [comment]
Closed by https://github.com/stndrs/based_pg/commit/a48d7d709966ab58514def38ad80c6e8505e350c
